services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chordbook-sqlserver
    restart: "no"
    
    # postgres setting (only for local user)
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ChordBook_dev123!"
     
    # port mapping  
    ports:
      - "1433:1433"
    
    # save data outside the container
    volumes:
      - chordbook-sqlserver-data:/var/opt/mssql
  
# call volume
volumes:
  chordbook-sqlserver-data: