// <auto-generated />
using System;
using ChordBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChordBook.Migrations
{
    [DbContext(typeof(ChordBookDbContext))]
    partial class ChordBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChordBook.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ChordBook.Entities.Chord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fingering")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Chords");
                });

            modelBuilder.Entity("ChordBook.Entities.ChordPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CharacterIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("ChordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongLineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChordId");

                    b.HasIndex("SongLineId", "CharacterIndex")
                        .IsUnique();

                    b.ToTable("ChordPositions", t =>
                        {
                            t.HasCheckConstraint("CK_ChordPosition_CharacterIndex_NonNegative", "\"CharacterIndex\" >= 0");
                        });
                });

            modelBuilder.Entity("ChordBook.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Artist")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("ChordBook.Entities.SongCategory", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SongId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SongCategories");
                });

            modelBuilder.Entity("ChordBook.Entities.SongLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SongId", "LineNumber")
                        .IsUnique();

                    b.ToTable("SongLines", t =>
                        {
                            t.HasCheckConstraint("CK_SongLine_LineNumber_NonNegative", "\"LineNumber\" >= 0");
                        });
                });

            modelBuilder.Entity("ChordBook.Entities.ChordPosition", b =>
                {
                    b.HasOne("ChordBook.Entities.Chord", "Chord")
                        .WithMany("ChordPositions")
                        .HasForeignKey("ChordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChordBook.Entities.SongLine", "SongLine")
                        .WithMany("ChordPositions")
                        .HasForeignKey("SongLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chord");

                    b.Navigation("SongLine");
                });

            modelBuilder.Entity("ChordBook.Entities.SongCategory", b =>
                {
                    b.HasOne("ChordBook.Entities.Category", "Category")
                        .WithMany("SongCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordBook.Entities.Song", "Song")
                        .WithMany("SongCategories")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ChordBook.Entities.SongLine", b =>
                {
                    b.HasOne("ChordBook.Entities.Song", "Song")
                        .WithMany("Lines")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ChordBook.Entities.Category", b =>
                {
                    b.Navigation("SongCategories");
                });

            modelBuilder.Entity("ChordBook.Entities.Chord", b =>
                {
                    b.Navigation("ChordPositions");
                });

            modelBuilder.Entity("ChordBook.Entities.Song", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("SongCategories");
                });

            modelBuilder.Entity("ChordBook.Entities.SongLine", b =>
                {
                    b.Navigation("ChordPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
